### ISSUE TITLE
presenceprefix ist nicht implementiert

### ISSUE THREAD

**Issue by Atoggota** [jollyjinx/homematic#1]
Die presenceprefix Variable ist nicht implementiert. So sollte es auch mit einem anderen Prefix (bei mir z.B. "Anwesenheit") funktionieren:

var presencevariable = dom.GetObject(presenceprefix#"."#personname);
        if( ispresent != presencevariable.Value() )
        {                                                                           if(debug){WriteLine("\t"#presenceprefix#"."#personname#" has changed:"#ispresent);}
            presencevariable.State(ispresent);
        }
        else
        {                                                                           if(debug){WriteLine("\t"#presenceprefix#"."#personname#" has not changed:"#ispresent);}
        }

**Comment by jollyjinx** [comment]
Ah - jetzt habe ich gesehen was Du meinst. Ist gefixt.
